# Generated by Django 5.0 on 2024-11-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='type',
            field=models.CharField(choices=[('entree', 'Entree'), ('side', 'Side'), ('appetizer', 'Appetizer'), ('dessert', 'Dessert'), ('drink', 'Drink')], default='entree', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderfoodquantity',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
