# Generated by Django 5.0 on 2024-11-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="alt_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="upcharge",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
