# Generated by Django 5.0 on 2024-12-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_zreport_datetime_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zreport',
            name='datetime_generated',
            field=models.DateTimeField(),
        ),
    ]
