# Generated by Django 5.0 on 2024-11-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_fooditem_alt_price_alter_fooditem_upcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='alt_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='upcharge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
