# Generated by Django 5.0 on 2024-11-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fooditem_alt_price_alter_fooditem_upcharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='order',
            name='date_processed',
            field=models.DateTimeField(null=True),
        ),
    ]
