# Generated by Django 5.0 on 2024-11-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_fooditem_alt_price_alter_fooditem_upcharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="food_images/"),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="is_gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="is_spicy",
            field=models.BooleanField(default=False),
        ),
    ]
