# Generated by Django 5.0 on 2024-11-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_date_order_date_created_order_date_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
